const SoundFiles = {
    "A0": require("../assets/sounds/acoustic_grand_piano_A0.mp3"),
    "A1": require("../assets/sounds/acoustic_grand_piano_A1.mp3"),
    "A2": require("../assets/sounds/acoustic_grand_piano_A2.mp3"),
    "A3": require("../assets/sounds/acoustic_grand_piano_A3.mp3"),
    "A4": require("../assets/sounds/acoustic_grand_piano_A4.mp3"),
    "A5": require("../assets/sounds/acoustic_grand_piano_A5.mp3"),
    "A6": require("../assets/sounds/acoustic_grand_piano_A6.mp3"),
    "A7": require("../assets/sounds/acoustic_grand_piano_A7.mp3"),
    
    "A#0": require("../assets/sounds/acoustic_grand_piano_A#0.mp3"),
    "A#1": require("../assets/sounds/acoustic_grand_piano_A#1.mp3"),
    "A#2": require("../assets/sounds/acoustic_grand_piano_A#2.mp3"),
    "A#3": require("../assets/sounds/acoustic_grand_piano_A#3.mp3"),
    "A#4": require("../assets/sounds/acoustic_grand_piano_A#4.mp3"),
    "A#5": require("../assets/sounds/acoustic_grand_piano_A#5.mp3"),
    "A#6": require("../assets/sounds/acoustic_grand_piano_A#6.mp3"),
    "A#7": require("../assets/sounds/acoustic_grand_piano_A#7.mp3"),
    
    "B0": require("../assets/sounds/acoustic_grand_piano_B0.mp3"),
    "B1": require("../assets/sounds/acoustic_grand_piano_B1.mp3"),
    "B2": require("../assets/sounds/acoustic_grand_piano_B2.mp3"),
    "B3": require("../assets/sounds/acoustic_grand_piano_B3.mp3"),
    "B4": require("../assets/sounds/acoustic_grand_piano_B4.mp3"),
    "B5": require("../assets/sounds/acoustic_grand_piano_B5.mp3"),
    "B6": require("../assets/sounds/acoustic_grand_piano_B6.mp3"),
    "B7": require("../assets/sounds/acoustic_grand_piano_B7.mp3"),

    "C1": require("../assets/sounds/acoustic_grand_piano_C1.mp3"),
    "C2": require("../assets/sounds/acoustic_grand_piano_C2.mp3"),
    "C3": require("../assets/sounds/acoustic_grand_piano_C3.mp3"),
    "C4": require("../assets/sounds/acoustic_grand_piano_C4.mp3"),
    "C5": require("../assets/sounds/acoustic_grand_piano_C5.mp3"),
    "C6": require("../assets/sounds/acoustic_grand_piano_C6.mp3"),
    "C7": require("../assets/sounds/acoustic_grand_piano_C7.mp3"),
    "C8": require("../assets/sounds/acoustic_grand_piano_C8.mp3"),
    
    "C#1": require("../assets/sounds/acoustic_grand_piano_C#1.mp3"),
    "C#2": require("../assets/sounds/acoustic_grand_piano_C#2.mp3"),
    "C#3": require("../assets/sounds/acoustic_grand_piano_C#3.mp3"),
    "C#4": require("../assets/sounds/acoustic_grand_piano_C#4.mp3"),
    "C#5": require("../assets/sounds/acoustic_grand_piano_C#5.mp3"),
    "C#6": require("../assets/sounds/acoustic_grand_piano_C#6.mp3"),
    "C#7": require("../assets/sounds/acoustic_grand_piano_C#7.mp3"),

    "D1": require("../assets/sounds/acoustic_grand_piano_D1.mp3"),
    "D2": require("../assets/sounds/acoustic_grand_piano_D2.mp3"),
    "D3": require("../assets/sounds/acoustic_grand_piano_D3.mp3"),
    "D4": require("../assets/sounds/acoustic_grand_piano_D4.mp3"),
    "D5": require("../assets/sounds/acoustic_grand_piano_D5.mp3"),
    "D6": require("../assets/sounds/acoustic_grand_piano_D6.mp3"),
    "D7": require("../assets/sounds/acoustic_grand_piano_D7.mp3"),
    
    "D#1": require("../assets/sounds/acoustic_grand_piano_D#1.mp3"),
    "D#2": require("../assets/sounds/acoustic_grand_piano_D#2.mp3"),
    "D#3": require("../assets/sounds/acoustic_grand_piano_D#3.mp3"),
    "D#4": require("../assets/sounds/acoustic_grand_piano_D#4.mp3"),
    "D#5": require("../assets/sounds/acoustic_grand_piano_D#5.mp3"),
    "D#6": require("../assets/sounds/acoustic_grand_piano_D#6.mp3"),
    "D#7": require("../assets/sounds/acoustic_grand_piano_D#7.mp3"),
    
    "E1": require("../assets/sounds/acoustic_grand_piano_E1.mp3"),
    "E2": require("../assets/sounds/acoustic_grand_piano_E2.mp3"),
    "E3": require("../assets/sounds/acoustic_grand_piano_E3.mp3"),
    "E4": require("../assets/sounds/acoustic_grand_piano_E4.mp3"),
    "E5": require("../assets/sounds/acoustic_grand_piano_E5.mp3"),
    "E6": require("../assets/sounds/acoustic_grand_piano_E6.mp3"),
    "E7": require("../assets/sounds/acoustic_grand_piano_E7.mp3"),

    "F1": require("../assets/sounds/acoustic_grand_piano_F1.mp3"),
    "F2": require("../assets/sounds/acoustic_grand_piano_F2.mp3"),
    "F3": require("../assets/sounds/acoustic_grand_piano_F3.mp3"),
    "F4": require("../assets/sounds/acoustic_grand_piano_F4.mp3"),
    "F5": require("../assets/sounds/acoustic_grand_piano_F5.mp3"),
    "F6": require("../assets/sounds/acoustic_grand_piano_F6.mp3"),
    "F7": require("../assets/sounds/acoustic_grand_piano_F7.mp3"),
    
    
    "F#1": require("../assets/sounds/acoustic_grand_piano_F#1.mp3"),
    "F#2": require("../assets/sounds/acoustic_grand_piano_F#2.mp3"),
    "F#3": require("../assets/sounds/acoustic_grand_piano_F#3.mp3"),
    "F#4": require("../assets/sounds/acoustic_grand_piano_F#4.mp3"),
    "F#5": require("../assets/sounds/acoustic_grand_piano_F#5.mp3"),
    "F#6": require("../assets/sounds/acoustic_grand_piano_F#6.mp3"),
    "F#7": require("../assets/sounds/acoustic_grand_piano_F#7.mp3"),

    "G1": require("../assets/sounds/acoustic_grand_piano_G1.mp3"),
    "G2": require("../assets/sounds/acoustic_grand_piano_G2.mp3"),
    "G3": require("../assets/sounds/acoustic_grand_piano_G3.mp3"),
    "G4": require("../assets/sounds/acoustic_grand_piano_G4.mp3"),
    "G5": require("../assets/sounds/acoustic_grand_piano_G5.mp3"),
    "G6": require("../assets/sounds/acoustic_grand_piano_G6.mp3"),
    "G7": require("../assets/sounds/acoustic_grand_piano_G7.mp3"),

    "G#1": require("../assets/sounds/acoustic_grand_piano_G#1.mp3"),
    "G#2": require("../assets/sounds/acoustic_grand_piano_G#2.mp3"),
    "G#3": require("../assets/sounds/acoustic_grand_piano_G#3.mp3"),
    "G#4": require("../assets/sounds/acoustic_grand_piano_G#4.mp3"),
    "G#5": require("../assets/sounds/acoustic_grand_piano_G#5.mp3"),
    "G#6": require("../assets/sounds/acoustic_grand_piano_G#6.mp3"),
    "G#7": require("../assets/sounds/acoustic_grand_piano_G#7.mp3"),
}

export default SoundFiles