const SoundFiles = {
    "A0": "a0.mp3",
    "A1": "a1.mp3",
    "A2": "a2.mp3",
    "A3": "a3.mp3",
    "A4": "a4.mp3",
    "A5": "a5.mp3",
    "A6": "a6.mp3",
    "A7": "a7.mp3",

    "Ab1": "ab1.mp3",
    "Ab2": "ab2.mp3",
    "Ab3": "ab3.mp3",
    "Ab4": "ab4.mp3",
    "Ab5": "ab5.mp3",
    "Ab6": "ab6.mp3",
    "Ab7": "ab7.mp3",

    "B0": "b0.mp3",
    "B1": "b1.mp3",
    "B2": "b2.mp3",
    "B3": "b3.mp3",
    "B4": "b4.mp3",
    "B5": "b5.mp3",
    "B6": "b6.mp3",
    "B7": "b7.mp3",

    "Bb0": "bb0.mp3",
    "Bb1": "bb1.mp3",
    "Bb2": "bb2.mp3",
    "Bb3": "bb3.mp3",
    "Bb4": "bb4.mp3",
    "Bb5": "bb5.mp3",
    "Bb6": "bb6.mp3",
    "Bb7": "bb7.mp3",

    "C1": "c1.mp3",
    "C2": "c2.mp3",
    "C3": "c3.mp3",
    "C4": "c4.mp3",
    "C5": "c5.mp3",
    "C6": "c6.mp3",
    "C7": "c7.mp3",
    "C8": "c8.mp3",

    "D1": "d1.mp3",
    "D2": "d2.mp3",
    "D3": "d3.mp3",
    "D4": "d4.mp3",
    "D5": "d5.mp3",
    "D6": "d6.mp3",
    "D7": "d7.mp3",

    "Db1": "db1.mp3",
    "Db2": "db2.mp3",
    "Db3": "db3.mp3",
    "Db4": "db4.mp3",
    "Db5": "db5.mp3",
    "Db6": "db6.mp3",
    "Db7": "db7.mp3",

    "E1": "e1.mp3",
    "E2": "e2.mp3",
    "E3": "e3.mp3",
    "E4": "e4.mp3",
    "E5": "e5.mp3",
    "E6": "e6.mp3",
    "E7": "e7.mp3",

    "Eb1": "eb1.mp3",
    "Eb2": "eb2.mp3",
    "Eb3": "eb3.mp3",
    "Eb4": "eb4.mp3",
    "Eb5": "eb5.mp3",
    "Eb6": "eb6.mp3",
    "Eb7": "eb7.mp3",

    "F1": "f1.mp3",
    "F2": "f2.mp3",
    "F3": "f3.mp3",
    "F4": "f4.mp3",
    "F5": "f5.mp3",
    "F6": "f6.mp3",
    "F7": "f7.mp3",

    "G1": "g1.mp3",
    "G2": "g2.mp3",
    "G3": "g3.mp3",
    "G4": "g4.mp3",
    "G5": "g5.mp3",
    "G6": "g6.mp3",
    "G7": "g7.mp3",

    "Gb1": "gb1.mp3",
    "Gb2": "gb2.mp3",
    "Gb3": "gb3.mp3",
    "Gb4": "gb4.mp3",
    "Gb5": "gb5.mp3",
    "Gb6": "gb6.mp3",
    "Gb7": "gb7.mp3",
}

const SoundFilesOld = [
    "a0.mp3",
    "a1.mp3",
    "a2.mp3",
    "a3.mp3",
    "a4.mp3",
    "a5.mp3",
    "a6.mp3",
    "a7.mp3",
    "ab1.mp3",
    "ab2.mp3",
    "ab3.mp3",
    "ab4.mp3",
    "ab5.mp3",
    "ab6.mp3",
    "ab7.mp3",
    "b0.mp3",
    "b1.mp3",
    "b2.mp3",
    "b3.mp3",
    "b4.mp3",
    "b5.mp3",
    "b6.mp3",
    "b7.mp3",
    "bb0.mp3",
    "bb1.mp3",
    "bb2.mp3",
    "bb3.mp3",
    "bb4.mp3",
    "bb5.mp3",
    "bb6.mp3",
    "bb7.mp3",
    "c1.mp3",
    "c2.mp3",
    "c3.mp3",
    "c4.mp3",
    "c5.mp3",
    "c6.mp3",
    "c7.mp3",
    "c8.mp3",
    "d1.mp3",
    "d2.mp3",
    "d3.mp3",
    "d4.mp3",
    "d5.mp3",
    "d6.mp3",
    "d7.mp3",
    "db1.mp3",
    "db2.mp3",
    "db3.mp3",
    "db4.mp3",
    "db5.mp3",
    "db6.mp3",
    "db7.mp3",
    "e1.mp3",
    "e2.mp3",
    "e3.mp3",
    "e4.mp3",
    "e5.mp3",
    "e6.mp3",
    "e7.mp3",
    "eb1.mp3",
    "eb2.mp3",
    "eb3.mp3",
    "eb4.mp3",
    "eb5.mp3",
    "eb6.mp3",
    "eb7.mp3",
    "f1.mp3",
    "f2.mp3",
    "f3.mp3",
    "f4.mp3",
    "f5.mp3",
    "f6.mp3",
    "f7.mp3",
    "g1.mp3",
    "g2.mp3",
    "g3.mp3",
    "g4.mp3",
    "g5.mp3",
    "g6.mp3",
    "g7.mp3",
    "gb1.mp3",
    "gb2.mp3",
    "gb3.mp3",
    "gb4.mp3",
    "gb5.mp3",
    "gb6.mp3",
    "gb7.mp3",
]

const SoundFilesOld2 = {
    "A0": require("../assets/sounds/acoustic_grand_piano_A0.mp3"),
    "A1": require("../assets/sounds/acoustic_grand_piano_A1.mp3"),
    "A2": require("../assets/sounds/acoustic_grand_piano_A2.mp3"),
    "A3": require("../assets/sounds/acoustic_grand_piano_A3.mp3"),
    "A4": require("../assets/sounds/acoustic_grand_piano_A4.mp3"),
    "A5": require("../assets/sounds/acoustic_grand_piano_A5.mp3"),
    "A6": require("../assets/sounds/acoustic_grand_piano_A6.mp3"),
    "A7": require("../assets/sounds/acoustic_grand_piano_A7.mp3"),

    "Ab1": require("../assets/sounds/acoustic_grand_piano_Ab1.mp3"),
    "Ab2": require("../assets/sounds/acoustic_grand_piano_Ab2.mp3"),
    "Ab3": require("../assets/sounds/acoustic_grand_piano_Ab3.mp3"),
    "Ab4": require("../assets/sounds/acoustic_grand_piano_Ab4.mp3"),
    "Ab5": require("../assets/sounds/acoustic_grand_piano_Ab5.mp3"),
    "Ab6": require("../assets/sounds/acoustic_grand_piano_Ab6.mp3"),
    "Ab7": require("../assets/sounds/acoustic_grand_piano_Ab7.mp3"),

    "B0": require("../assets/sounds/acoustic_grand_piano_B0.mp3"),
    "B1": require("../assets/sounds/acoustic_grand_piano_B1.mp3"),
    "B2": require("../assets/sounds/acoustic_grand_piano_B2.mp3"),
    "B3": require("../assets/sounds/acoustic_grand_piano_B3.mp3"),
    "B4": require("../assets/sounds/acoustic_grand_piano_B4.mp3"),
    "B5": require("../assets/sounds/acoustic_grand_piano_B5.mp3"),
    "B6": require("../assets/sounds/acoustic_grand_piano_B6.mp3"),
    "B7": require("../assets/sounds/acoustic_grand_piano_B7.mp3"),

    "Bb0": require("../assets/sounds/acoustic_grand_piano_Bb0.mp3"),
    "Bb1": require("../assets/sounds/acoustic_grand_piano_Bb1.mp3"),
    "Bb2": require("../assets/sounds/acoustic_grand_piano_Bb2.mp3"),
    "Bb3": require("../assets/sounds/acoustic_grand_piano_Bb3.mp3"),
    "Bb4": require("../assets/sounds/acoustic_grand_piano_Bb4.mp3"),
    "Bb5": require("../assets/sounds/acoustic_grand_piano_Bb5.mp3"),
    "Bb6": require("../assets/sounds/acoustic_grand_piano_Bb6.mp3"),
    "Bb7": require("../assets/sounds/acoustic_grand_piano_Bb7.mp3"),

    "C1": require("../assets/sounds/acoustic_grand_piano_C1.mp3"),
    "C2": require("../assets/sounds/acoustic_grand_piano_C2.mp3"),
    "C3": require("../assets/sounds/acoustic_grand_piano_C3.mp3"),
    "C4": require("../assets/sounds/acoustic_grand_piano_C4.mp3"),
    "C5": require("../assets/sounds/acoustic_grand_piano_C5.mp3"),
    "C6": require("../assets/sounds/acoustic_grand_piano_C6.mp3"),
    "C7": require("../assets/sounds/acoustic_grand_piano_C7.mp3"),
    "C8": require("../assets/sounds/acoustic_grand_piano_C8.mp3"),

    "D1": require("../assets/sounds/acoustic_grand_piano_D1.mp3"),
    "D2": require("../assets/sounds/acoustic_grand_piano_D2.mp3"),
    "D3": require("../assets/sounds/acoustic_grand_piano_D3.mp3"),
    "D4": require("../assets/sounds/acoustic_grand_piano_D4.mp3"),
    "D5": require("../assets/sounds/acoustic_grand_piano_D5.mp3"),
    "D6": require("../assets/sounds/acoustic_grand_piano_D6.mp3"),
    "D7": require("../assets/sounds/acoustic_grand_piano_D7.mp3"),

    "Db1": require("../assets/sounds/acoustic_grand_piano_Db1.mp3"),
    "Db2": require("../assets/sounds/acoustic_grand_piano_Db2.mp3"),
    "Db3": require("../assets/sounds/acoustic_grand_piano_Db3.mp3"),
    "Db4": require("../assets/sounds/acoustic_grand_piano_Db4.mp3"),
    "Db5": require("../assets/sounds/acoustic_grand_piano_Db5.mp3"),
    "Db6": require("../assets/sounds/acoustic_grand_piano_Db6.mp3"),
    "Db7": require("../assets/sounds/acoustic_grand_piano_Db7.mp3"),

    "E1": require("../assets/sounds/acoustic_grand_piano_E1.mp3"),
    "E2": require("../assets/sounds/acoustic_grand_piano_E2.mp3"),
    "E3": require("../assets/sounds/acoustic_grand_piano_E3.mp3"),
    "E4": require("../assets/sounds/acoustic_grand_piano_E4.mp3"),
    "E5": require("../assets/sounds/acoustic_grand_piano_E5.mp3"),
    "E6": require("../assets/sounds/acoustic_grand_piano_E6.mp3"),
    "E7": require("../assets/sounds/acoustic_grand_piano_E7.mp3"),

    "Eb1": require("../assets/sounds/acoustic_grand_piano_Eb1.mp3"),
    "Eb2": require("../assets/sounds/acoustic_grand_piano_Eb2.mp3"),
    "Eb3": require("../assets/sounds/acoustic_grand_piano_Eb3.mp3"),
    "Eb4": require("../assets/sounds/acoustic_grand_piano_Eb4.mp3"),
    "Eb5": require("../assets/sounds/acoustic_grand_piano_Eb5.mp3"),
    "Eb6": require("../assets/sounds/acoustic_grand_piano_Eb6.mp3"),
    "Eb7": require("../assets/sounds/acoustic_grand_piano_Eb7.mp3"),

    "F1": require("../assets/sounds/acoustic_grand_piano_F1.mp3"),
    "F2": require("../assets/sounds/acoustic_grand_piano_F2.mp3"),
    "F3": require("../assets/sounds/acoustic_grand_piano_F3.mp3"),
    "F4": require("../assets/sounds/acoustic_grand_piano_F4.mp3"),
    "F5": require("../assets/sounds/acoustic_grand_piano_F5.mp3"),
    "F6": require("../assets/sounds/acoustic_grand_piano_F6.mp3"),
    "F7": require("../assets/sounds/acoustic_grand_piano_F7.mp3"),

    "G1": require("../assets/sounds/acoustic_grand_piano_G1.mp3"),
    "G2": require("../assets/sounds/acoustic_grand_piano_G2.mp3"),
    "G3": require("../assets/sounds/acoustic_grand_piano_G3.mp3"),
    "G4": require("../assets/sounds/acoustic_grand_piano_G4.mp3"),
    "G5": require("../assets/sounds/acoustic_grand_piano_G5.mp3"),
    "G6": require("../assets/sounds/acoustic_grand_piano_G6.mp3"),
    "G7": require("../assets/sounds/acoustic_grand_piano_G7.mp3"),

    "Gb1": require("../assets/sounds/acoustic_grand_piano_Gb1.mp3"),
    "Gb2": require("../assets/sounds/acoustic_grand_piano_Gb2.mp3"),
    "Gb3": require("../assets/sounds/acoustic_grand_piano_Gb3.mp3"),
    "Gb4": require("../assets/sounds/acoustic_grand_piano_Gb4.mp3"),
    "Gb5": require("../assets/sounds/acoustic_grand_piano_Gb5.mp3"),
    "Gb6": require("../assets/sounds/acoustic_grand_piano_Gb6.mp3"),
    "Gb7": require("../assets/sounds/acoustic_grand_piano_Gb7.mp3"),
}

export default SoundFiles